import "../styles/globals.scss";
import type { AppProps } from "next/app";
import { StyledEngineProvider, ThemeProvider } from "@mui/material";
import { theme } from "../styles/theme";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../src/components/Navbar";
import NewTokenProvider from "../src/components/newToken";
function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const path = router.pathname;
  return (
    <>
      <Head>
        <title>My playlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledEngineProvider>
        <ThemeProvider theme={theme}>
          <NewTokenProvider>
            {path !== "/" ? <Navbar /> : ""}
            <Component {...pageProps} />
          </NewTokenProvider>
        </ThemeProvider>
      </StyledEngineProvider>
    </>
  );
}

export default MyApp;
